/*
 * Headless Admin User
 * A Java client JAR is available for use with the group ID 'com.liferay', artifact ID 'com.liferay.headless.admin.user.client', and version '4.0.49'.
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.liferay.headless.admin.user.client.api;

import com.liferay.headless.admin.user.client.model.EmailAddress;
import com.liferay.headless.admin.user.client.model.PageEmailAddress;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for EmailAddressApi
 */
@Ignore
public class EmailAddressApiTest {

    private final EmailAddressApi api = new EmailAddressApi();

    /**
     * 
     *
     * Retrieves the email address.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getEmailAddressTest() throws Exception {
        String emailAddressId = null;
        EmailAddress response = api.getEmailAddress(emailAddressId);

        // TODO: test validations
    }
    /**
     * 
     *
     * Retrieves the organization&#x27;s email addresses.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getOrganizationEmailAddressesPageTest() throws Exception {
        String organizationId = null;
        PageEmailAddress response = api.getOrganizationEmailAddressesPage(organizationId);

        // TODO: test validations
    }
    /**
     * 
     *
     * Retrieves the user&#x27;s email addresses.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getUserAccountEmailAddressesPageTest() throws Exception {
        String userAccountId = null;
        PageEmailAddress response = api.getUserAccountEmailAddressesPage(userAccountId);

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void postOrganizationEmailAddressesPageExportBatchTest() throws Exception {
        String organizationId = null;
        String callbackURL = null;
        String contentType = null;
        String fieldNames = null;
        api.postOrganizationEmailAddressesPageExportBatch(organizationId, callbackURL, contentType, fieldNames);

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void postUserAccountEmailAddressesPageExportBatchTest() throws Exception {
        String userAccountId = null;
        String callbackURL = null;
        String contentType = null;
        String fieldNames = null;
        api.postUserAccountEmailAddressesPageExportBatch(userAccountId, callbackURL, contentType, fieldNames);

        // TODO: test validations
    }
}
