/*
 * Headless Admin User
 * A Java client JAR is available for use with the group ID 'com.liferay', artifact ID 'com.liferay.headless.admin.user.client', and version '4.0.49'.
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.liferay.headless.admin.user.client.api;

import com.liferay.headless.admin.user.client.model.PageSegmentUser;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for SegmentUserApi
 */
@Ignore
public class SegmentUserApiTest {

    private final SegmentUserApi api = new SegmentUserApi();

    /**
     * 
     *
     * Gets a segment&#x27;s users.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getSegmentUserAccountsPageTest() throws Exception {
        String segmentId = null;
        String page = null;
        String pageSize = null;
        PageSegmentUser response = api.getSegmentUserAccountsPage(segmentId, page, pageSize);

        // TODO: test validations
    }
}
