/*
 * Headless Admin User
 * A Java client JAR is available for use with the group ID 'com.liferay', artifact ID 'com.liferay.headless.admin.user.client', and version '4.0.49'.
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.liferay.headless.admin.user.client.api;

import com.liferay.headless.admin.user.client.model.PageWebUrl;
import com.liferay.headless.admin.user.client.model.WebUrl;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for WebUrlApi
 */
@Ignore
public class WebUrlApiTest {

    private final WebUrlApi api = new WebUrlApi();

    /**
     * 
     *
     * Retrieves the organization&#x27;s URLs.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getOrganizationWebUrlsPageTest() throws Exception {
        String organizationId = null;
        PageWebUrl response = api.getOrganizationWebUrlsPage(organizationId);

        // TODO: test validations
    }
    /**
     * 
     *
     * Retrieves the user&#x27;s URLs.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getUserAccountWebUrlsPageTest() throws Exception {
        String userAccountId = null;
        PageWebUrl response = api.getUserAccountWebUrlsPage(userAccountId);

        // TODO: test validations
    }
    /**
     * 
     *
     * Retrieves the web URL.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getWebUrlTest() throws Exception {
        String webUrlId = null;
        WebUrl response = api.getWebUrl(webUrlId);

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void postOrganizationWebUrlsPageExportBatchTest() throws Exception {
        String organizationId = null;
        String callbackURL = null;
        String contentType = null;
        String fieldNames = null;
        api.postOrganizationWebUrlsPageExportBatch(organizationId, callbackURL, contentType, fieldNames);

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void postUserAccountWebUrlsPageExportBatchTest() throws Exception {
        String userAccountId = null;
        String callbackURL = null;
        String contentType = null;
        String fieldNames = null;
        api.postUserAccountWebUrlsPageExportBatch(userAccountId, callbackURL, contentType, fieldNames);

        // TODO: test validations
    }
}
