/*
 * Headless Admin User
 * A Java client JAR is available for use with the group ID 'com.liferay', artifact ID 'com.liferay.headless.admin.user.client', and version '4.0.49'.
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.liferay.headless.admin.user.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.liferay.headless.admin.user.client.model.CustomValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * CustomField
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-03-04T10:04:24.474623+08:00[Asia/Shanghai]")

public class CustomField {
  @SerializedName("customValue")
  private CustomValue customValue = null;

  @SerializedName("dataType")
  private String dataType = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("x-class-name")
  private String xClassName = "com.liferay.headless.admin.user.dto.v1_0.CustomField";

  public CustomField customValue(CustomValue customValue) {
    this.customValue = customValue;
    return this;
  }

   /**
   * Get customValue
   * @return customValue
  **/
  @Schema(description = "")
  public CustomValue getCustomValue() {
    return customValue;
  }

  public void setCustomValue(CustomValue customValue) {
    this.customValue = customValue;
  }

   /**
   * The field type (e.g., image, text, etc.).
   * @return dataType
  **/
  @Schema(description = "The field type (e.g., image, text, etc.).")
  public String getDataType() {
    return dataType;
  }

  public CustomField name(String name) {
    this.name = name;
    return this;
  }

   /**
   * The field&#x27;s internal name. This is valid for comparisons and unique in the structured content.
   * @return name
  **/
  @Schema(description = "The field's internal name. This is valid for comparisons and unique in the structured content.")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

   /**
   * Get xClassName
   * @return xClassName
  **/
  @Schema(description = "")
  public String getXClassName() {
    return xClassName;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CustomField customField = (CustomField) o;
    return Objects.equals(this.customValue, customField.customValue) &&
        Objects.equals(this.dataType, customField.dataType) &&
        Objects.equals(this.name, customField.name) &&
        Objects.equals(this.xClassName, customField.xClassName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(customValue, dataType, name, xClassName);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CustomField {\n");
    
    sb.append("    customValue: ").append(toIndentedString(customValue)).append("\n");
    sb.append("    dataType: ").append(toIndentedString(dataType)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    xClassName: ").append(toIndentedString(xClassName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
