/*
 * Headless Admin User
 * A Java client JAR is available for use with the group ID 'com.liferay', artifact ID 'com.liferay.headless.admin.user.client', and version '4.0.49'.
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.liferay.headless.admin.user.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.liferay.headless.admin.user.client.model.FacetValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * Facet
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-03-04T10:04:24.474623+08:00[Asia/Shanghai]")

public class Facet {
  @SerializedName("facetCriteria")
  private String facetCriteria = null;

  @SerializedName("facetValues")
  private List<FacetValue> facetValues = null;

  public Facet facetCriteria(String facetCriteria) {
    this.facetCriteria = facetCriteria;
    return this;
  }

   /**
   * Get facetCriteria
   * @return facetCriteria
  **/
  @Schema(description = "")
  public String getFacetCriteria() {
    return facetCriteria;
  }

  public void setFacetCriteria(String facetCriteria) {
    this.facetCriteria = facetCriteria;
  }

  public Facet facetValues(List<FacetValue> facetValues) {
    this.facetValues = facetValues;
    return this;
  }

  public Facet addFacetValuesItem(FacetValue facetValuesItem) {
    if (this.facetValues == null) {
      this.facetValues = new ArrayList<FacetValue>();
    }
    this.facetValues.add(facetValuesItem);
    return this;
  }

   /**
   * Get facetValues
   * @return facetValues
  **/
  @Schema(description = "")
  public List<FacetValue> getFacetValues() {
    return facetValues;
  }

  public void setFacetValues(List<FacetValue> facetValues) {
    this.facetValues = facetValues;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Facet facet = (Facet) o;
    return Objects.equals(this.facetCriteria, facet.facetCriteria) &&
        Objects.equals(this.facetValues, facet.facetValues);
  }

  @Override
  public int hashCode() {
    return Objects.hash(facetCriteria, facetValues);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Facet {\n");
    
    sb.append("    facetCriteria: ").append(toIndentedString(facetCriteria)).append("\n");
    sb.append("    facetValues: ").append(toIndentedString(facetValues)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
