/*
 * Headless Admin User
 * A Java client JAR is available for use with the group ID 'com.liferay', artifact ID 'com.liferay.headless.admin.user.client', and version '4.0.49'.
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.liferay.headless.admin.user.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.liferay.headless.admin.user.client.model.RoleBrief;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * A list of the user&#x27;s organizations.
 */
@Schema(description = "A list of the user's organizations.")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-03-04T10:04:24.474623+08:00[Asia/Shanghai]")

public class OrganizationBrief {
  @SerializedName("id")
  private Long id = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("roleBriefs")
  private List<RoleBrief> roleBriefs = null;

  @SerializedName("x-class-name")
  private String xClassName = "com.liferay.headless.admin.user.dto.v1_0.OrganizationBrief";

   /**
   * The organization&#x27;s ID.
   * @return id
  **/
  @Schema(description = "The organization's ID.")
  public Long getId() {
    return id;
  }

   /**
   * The organization&#x27;s name.
   * @return name
  **/
  @Schema(description = "The organization's name.")
  public String getName() {
    return name;
  }

   /**
   * A list of the user&#x27;s roles.
   * @return roleBriefs
  **/
  @Schema(description = "A list of the user's roles.")
  public List<RoleBrief> getRoleBriefs() {
    return roleBriefs;
  }

   /**
   * Get xClassName
   * @return xClassName
  **/
  @Schema(description = "")
  public String getXClassName() {
    return xClassName;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrganizationBrief organizationBrief = (OrganizationBrief) o;
    return Objects.equals(this.id, organizationBrief.id) &&
        Objects.equals(this.name, organizationBrief.name) &&
        Objects.equals(this.roleBriefs, organizationBrief.roleBriefs) &&
        Objects.equals(this.xClassName, organizationBrief.xClassName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, roleBriefs, xClassName);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrganizationBrief {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    roleBriefs: ").append(toIndentedString(roleBriefs)).append("\n");
    sb.append("    xClassName: ").append(toIndentedString(xClassName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
