/*
 * Headless Admin User
 * A Java client JAR is available for use with the group ID 'com.liferay', artifact ID 'com.liferay.headless.admin.user.client', and version '4.0.49'.
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.liferay.headless.admin.user.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
/**
 * A list of the user&#x27;s roles.
 */
@Schema(description = "A list of the user's roles.")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-03-04T10:04:24.474623+08:00[Asia/Shanghai]")

public class RoleBrief {
  @SerializedName("id")
  private Long id = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("name_i18n")
  private Map<String, String> nameI18n = null;

  @SerializedName("x-class-name")
  private String xClassName = "com.liferay.headless.admin.user.dto.v1_0.RoleBrief";

   /**
   * The role&#x27;s ID.
   * @return id
  **/
  @Schema(description = "The role's ID.")
  public Long getId() {
    return id;
  }

   /**
   * The role&#x27;s name.
   * @return name
  **/
  @Schema(description = "The role's name.")
  public String getName() {
    return name;
  }

   /**
   * Get nameI18n
   * @return nameI18n
  **/
  @Schema(description = "")
  public Map<String, String> getNameI18n() {
    return nameI18n;
  }

   /**
   * Get xClassName
   * @return xClassName
  **/
  @Schema(description = "")
  public String getXClassName() {
    return xClassName;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RoleBrief roleBrief = (RoleBrief) o;
    return Objects.equals(this.id, roleBrief.id) &&
        Objects.equals(this.name, roleBrief.name) &&
        Objects.equals(this.nameI18n, roleBrief.nameI18n) &&
        Objects.equals(this.xClassName, roleBrief.xClassName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, nameI18n, xClassName);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RoleBrief {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    nameI18n: ").append(toIndentedString(nameI18n)).append("\n");
    sb.append("    xClassName: ").append(toIndentedString(xClassName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
