/*
 * Headless Admin User
 * A Java client JAR is available for use with the group ID 'com.liferay', artifact ID 'com.liferay.headless.admin.user.client', and version '4.0.49'.
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.liferay.headless.admin.user.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.liferay.headless.admin.user.client.model.EmailAddress;
import com.liferay.headless.admin.user.client.model.Phone;
import com.liferay.headless.admin.user.client.model.PostalAddress;
import com.liferay.headless.admin.user.client.model.WebUrl;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * The user&#x27;s contact information.
 */
@Schema(description = "The user's contact information.")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-03-04T10:04:24.474623+08:00[Asia/Shanghai]")

public class UserAccountContactInformation {
  @SerializedName("emailAddresses")
  private List<EmailAddress> emailAddresses = null;

  @SerializedName("facebook")
  private String facebook = null;

  @SerializedName("id")
  private Long id = null;

  @SerializedName("jabber")
  private String jabber = null;

  @SerializedName("postalAddresses")
  private List<PostalAddress> postalAddresses = null;

  @SerializedName("skype")
  private String skype = null;

  @SerializedName("sms")
  private String sms = null;

  @SerializedName("telephones")
  private List<Phone> telephones = null;

  @SerializedName("twitter")
  private String twitter = null;

  @SerializedName("webUrls")
  private List<WebUrl> webUrls = null;

  @SerializedName("x-class-name")
  private String xClassName = "com.liferay.headless.admin.user.dto.v1_0.UserAccountContactInformation";

  public UserAccountContactInformation emailAddresses(List<EmailAddress> emailAddresses) {
    this.emailAddresses = emailAddresses;
    return this;
  }

  public UserAccountContactInformation addEmailAddressesItem(EmailAddress emailAddressesItem) {
    if (this.emailAddresses == null) {
      this.emailAddresses = new ArrayList<EmailAddress>();
    }
    this.emailAddresses.add(emailAddressesItem);
    return this;
  }

   /**
   * A list of the user&#x27;s email addresses, with one optionally marked as primary.
   * @return emailAddresses
  **/
  @Schema(description = "A list of the user's email addresses, with one optionally marked as primary.")
  public List<EmailAddress> getEmailAddresses() {
    return emailAddresses;
  }

  public void setEmailAddresses(List<EmailAddress> emailAddresses) {
    this.emailAddresses = emailAddresses;
  }

  public UserAccountContactInformation facebook(String facebook) {
    this.facebook = facebook;
    return this;
  }

   /**
   * The user&#x27;s Facebook account.
   * @return facebook
  **/
  @Schema(description = "The user's Facebook account.")
  public String getFacebook() {
    return facebook;
  }

  public void setFacebook(String facebook) {
    this.facebook = facebook;
  }

   /**
   * The ID of the &#x60;contactInformation&#x60;.
   * @return id
  **/
  @Schema(description = "The ID of the `contactInformation`.")
  public Long getId() {
    return id;
  }

  public UserAccountContactInformation jabber(String jabber) {
    this.jabber = jabber;
    return this;
  }

   /**
   * The user&#x27;s Jabber handle.
   * @return jabber
  **/
  @Schema(description = "The user's Jabber handle.")
  public String getJabber() {
    return jabber;
  }

  public void setJabber(String jabber) {
    this.jabber = jabber;
  }

  public UserAccountContactInformation postalAddresses(List<PostalAddress> postalAddresses) {
    this.postalAddresses = postalAddresses;
    return this;
  }

  public UserAccountContactInformation addPostalAddressesItem(PostalAddress postalAddressesItem) {
    if (this.postalAddresses == null) {
      this.postalAddresses = new ArrayList<PostalAddress>();
    }
    this.postalAddresses.add(postalAddressesItem);
    return this;
  }

   /**
   * A list of user&#x27;s postal addresses, with one optionally marked as primary.
   * @return postalAddresses
  **/
  @Schema(description = "A list of user's postal addresses, with one optionally marked as primary.")
  public List<PostalAddress> getPostalAddresses() {
    return postalAddresses;
  }

  public void setPostalAddresses(List<PostalAddress> postalAddresses) {
    this.postalAddresses = postalAddresses;
  }

  public UserAccountContactInformation skype(String skype) {
    this.skype = skype;
    return this;
  }

   /**
   * The user&#x27;s Skype handle.
   * @return skype
  **/
  @Schema(description = "The user's Skype handle.")
  public String getSkype() {
    return skype;
  }

  public void setSkype(String skype) {
    this.skype = skype;
  }

  public UserAccountContactInformation sms(String sms) {
    this.sms = sms;
    return this;
  }

   /**
   * The user&#x27;s SMS number.
   * @return sms
  **/
  @Schema(description = "The user's SMS number.")
  public String getSms() {
    return sms;
  }

  public void setSms(String sms) {
    this.sms = sms;
  }

  public UserAccountContactInformation telephones(List<Phone> telephones) {
    this.telephones = telephones;
    return this;
  }

  public UserAccountContactInformation addTelephonesItem(Phone telephonesItem) {
    if (this.telephones == null) {
      this.telephones = new ArrayList<Phone>();
    }
    this.telephones.add(telephonesItem);
    return this;
  }

   /**
   * A list of the user&#x27;s phone numbers, with one optionally marked as primary.
   * @return telephones
  **/
  @Schema(description = "A list of the user's phone numbers, with one optionally marked as primary.")
  public List<Phone> getTelephones() {
    return telephones;
  }

  public void setTelephones(List<Phone> telephones) {
    this.telephones = telephones;
  }

  public UserAccountContactInformation twitter(String twitter) {
    this.twitter = twitter;
    return this;
  }

   /**
   * The user&#x27;s Twitter handle.
   * @return twitter
  **/
  @Schema(description = "The user's Twitter handle.")
  public String getTwitter() {
    return twitter;
  }

  public void setTwitter(String twitter) {
    this.twitter = twitter;
  }

  public UserAccountContactInformation webUrls(List<WebUrl> webUrls) {
    this.webUrls = webUrls;
    return this;
  }

  public UserAccountContactInformation addWebUrlsItem(WebUrl webUrlsItem) {
    if (this.webUrls == null) {
      this.webUrls = new ArrayList<WebUrl>();
    }
    this.webUrls.add(webUrlsItem);
    return this;
  }

   /**
   * A list of the user&#x27;s web URLs, with one optionally marked as primary.
   * @return webUrls
  **/
  @Schema(description = "A list of the user's web URLs, with one optionally marked as primary.")
  public List<WebUrl> getWebUrls() {
    return webUrls;
  }

  public void setWebUrls(List<WebUrl> webUrls) {
    this.webUrls = webUrls;
  }

   /**
   * Get xClassName
   * @return xClassName
  **/
  @Schema(description = "")
  public String getXClassName() {
    return xClassName;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserAccountContactInformation userAccountContactInformation = (UserAccountContactInformation) o;
    return Objects.equals(this.emailAddresses, userAccountContactInformation.emailAddresses) &&
        Objects.equals(this.facebook, userAccountContactInformation.facebook) &&
        Objects.equals(this.id, userAccountContactInformation.id) &&
        Objects.equals(this.jabber, userAccountContactInformation.jabber) &&
        Objects.equals(this.postalAddresses, userAccountContactInformation.postalAddresses) &&
        Objects.equals(this.skype, userAccountContactInformation.skype) &&
        Objects.equals(this.sms, userAccountContactInformation.sms) &&
        Objects.equals(this.telephones, userAccountContactInformation.telephones) &&
        Objects.equals(this.twitter, userAccountContactInformation.twitter) &&
        Objects.equals(this.webUrls, userAccountContactInformation.webUrls) &&
        Objects.equals(this.xClassName, userAccountContactInformation.xClassName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(emailAddresses, facebook, id, jabber, postalAddresses, skype, sms, telephones, twitter, webUrls, xClassName);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserAccountContactInformation {\n");
    
    sb.append("    emailAddresses: ").append(toIndentedString(emailAddresses)).append("\n");
    sb.append("    facebook: ").append(toIndentedString(facebook)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    jabber: ").append(toIndentedString(jabber)).append("\n");
    sb.append("    postalAddresses: ").append(toIndentedString(postalAddresses)).append("\n");
    sb.append("    skype: ").append(toIndentedString(skype)).append("\n");
    sb.append("    sms: ").append(toIndentedString(sms)).append("\n");
    sb.append("    telephones: ").append(toIndentedString(telephones)).append("\n");
    sb.append("    twitter: ").append(toIndentedString(twitter)).append("\n");
    sb.append("    webUrls: ").append(toIndentedString(webUrls)).append("\n");
    sb.append("    xClassName: ").append(toIndentedString(xClassName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
